//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_producto
    {
        public int pro_id { get; set; }
        public string pro_nombre { get; set; }
        public string pro_imagen { get; set; }
        public string pro_descrip { get; set; }
        public Nullable<int> pro_precio { get; set; }
        public Nullable<int> pro_fk_user { get; set; }
        public Nullable<int> pro_fk_cat { get; set; }
    
        public virtual tbl_categoria tbl_categoria { get; set; }
        public virtual tbl_usuario tbl_usuario { get; set; }
    }
}
